### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by rickity-cricket** [javatlacati/contiperf#2]
I wonder if you know there is a GPL license hidden in your Profile class? (undeclared in README)
(Also a quadruple license is very silly imo, I think you should read them all and pick at most 2)

Options:
Remove the GPL license 
or
Accept that your entire project is GPL (read the GPL license if you don't believe me)

Have a great day!

J

**Comment by glatfi** [comment]
Hi @javatlacati 
Is it fine for you to remove all GPL license references in the code?
This is a blocking issue as the quadruple license is not valid as long as the source files mentions GPL.
I can create a PR.
Thank you

**Comment by javatlacati** [comment]
Feel free to open a PR is some GPL is remaining
